name: Validación Frontend

on:
  push:
    branches: [main]  # Se ejecuta cuando haces push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Mostrar archivos del proyecto
      run: ls -R

    - name: Validar HTML con htmlhint
      run: |
        npm install -g htmlhint
        htmlhint index.html || exit 1

    - name: Validar JS con eslint
      run: |
        npm install -g eslint
        eslint script.js || exit 1
