name: Validación Frontend

on:
  push:
    branches: [main]  # Puedes cambiar 'main' por otra rama si la usas

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: pinga
        uses: actions/checkout@v4

      - name: gadiel
        run: ls -R

      - name: Verificar Codigo HTML
        run: |
          npm install -g htmlhint
          htmlhint plubic/index.html || exit 1

      - name: Verificar Codigo JavaScript
        run: |
          npm install -g eslint@8
          eslint public/script.js || exit 1
      
      - name: Verificar Codigo CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
          stylelint public/style.css || exit 1

