name: Validación Frontend

on:
  push:
    branches: [main]  # Puedes cambiar 'main' por otra rama si la usas

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar archivos del proyecto
        run: ls -R

      - name: Instalar HTMLHint
        run: |
          npm install -g htmlhint
          htmlhint index.html || exit 1

      - name: Instalar ESLint versión 8
        run: |
          npm install -g eslint@8
          eslint script.js || exit 1
      
      - name: Instalar Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
          stylelint style.css || exit 1

